#!/bin/bash

source "$(pwd)/venv/bin/activate"

echo "TRIGUN"
echo "=============================================================================="
echo "File-Type 	:$(file $1 | awk -F ':' '{print $2}') "
echo "MD5 Hash	: $(md5sum $1 | awk '{print $1}') "
echo "SHA-256 Hash 	: $(sha256sum $1 | awk '{print $1}') "
echo "IMPHash		: $(python ./scripts/imphash.py $1) "
echo ""
echo "=========================== Fuzzy Hashing ===================================="
echo "$(ssdeep $1)"
echo ""
echo "========================== Section Hashing ==================================="
echo "$(python ./scripts/section_hashing.py $1)"
echo ""
echo "============================== Strings ======================================="
echo "Potential URLS"
echo "$(python ./scripts/strings_analyzer.py $1 url)"
echo ""
echo "Potential IPv4 addresses"
echo "$(python ./scripts/strings_analyzer.py $1 ipv4)"
echo ""
echo "Potential IPv6 addresses"
echo "$(python ./scripts/strings_analyzer.py $1 ipv6)"
echo ""
echo "Potential MAC addresses"
echo "$(python ./scripts/strings_analyzer.py $1 mac)"
echo ""
echo "Potential Mail addresses"
echo "$(python ./scripts/strings_analyzer.py $1 email)"
echo ""
echo "==================== Detecting Packers and Cryptors =========================="
echo "$(python ./scripts/packer_detection.py $1 ./rulesets/)"
echo ""
echo "======================= Known Malware Signatures ============================="
echo "$(python ./scripts/windows_signature.py $1 ./rulesets/)"
echo ""
echo "================================= Imports ===================================="
